{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.9.2)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Serv where
import Prelude (($), (.), (>>=), (==), (++))
import qualified Prelude as P
import qualified Control.Exception as X
import qualified Control.Monad as M ( liftM, ap, when )
import Data.Functor ( (<$>) )
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Hashable as H
import qualified Data.Int as I
import qualified Data.Maybe as M (catMaybes)
import qualified Data.Text.Lazy.Encoding as E ( decodeUtf8, encodeUtf8 )
import qualified Data.Text.Lazy as LT
import qualified Data.Typeable as TY ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector
import qualified Test.QuickCheck.Arbitrary as QC ( Arbitrary(..) )
import qualified Test.QuickCheck as QC ( elements )

import qualified Thrift as T
import qualified Thrift.Types as T
import qualified Thrift.Arbitraries as T


import Serv_Types
import qualified Serv_Iface as Iface
-- HELPER FUNCTIONS AND STRUCTURES --

data Ping_args = Ping_args deriving (P.Show,P.Eq,TY.Typeable)
instance H.Hashable Ping_args where
  hashWithSalt salt record = salt  
instance QC.Arbitrary Ping_args where 
  arbitrary = QC.elements [Ping_args]
from_Ping_args :: Ping_args -> T.ThriftVal
from_Ping_args record = T.TStruct $ Map.fromList $ M.catMaybes
  []
write_Ping_args :: (T.Protocol p, T.Transport t) => p t -> Ping_args -> P.IO ()
write_Ping_args oprot record = T.writeVal oprot $ from_Ping_args record
encode_Ping_args :: (T.Protocol p, T.Transport t) => p t -> Ping_args -> LBS.ByteString
encode_Ping_args oprot record = T.serializeVal oprot $ from_Ping_args record
to_Ping_args :: T.ThriftVal -> Ping_args
to_Ping_args (T.TStruct fields) = Ping_args{

  }
to_Ping_args _ = P.error "not a struct"
read_Ping_args :: (T.Transport t, T.Protocol p) => p t -> P.IO Ping_args
read_Ping_args iprot = to_Ping_args <$> T.readVal iprot (T.T_STRUCT typemap_Ping_args)
decode_Ping_args :: (T.Protocol p, T.Transport t) => p t -> LBS.ByteString -> Ping_args
decode_Ping_args iprot bs = to_Ping_args $ T.deserializeVal iprot (T.T_STRUCT typemap_Ping_args) bs
typemap_Ping_args :: T.TypeMap
typemap_Ping_args = Map.fromList []
default_Ping_args :: Ping_args
default_Ping_args = Ping_args{
}
data Ping_result = Ping_result deriving (P.Show,P.Eq,TY.Typeable)
instance H.Hashable Ping_result where
  hashWithSalt salt record = salt  
instance QC.Arbitrary Ping_result where 
  arbitrary = QC.elements [Ping_result]
from_Ping_result :: Ping_result -> T.ThriftVal
from_Ping_result record = T.TStruct $ Map.fromList $ M.catMaybes
  []
write_Ping_result :: (T.Protocol p, T.Transport t) => p t -> Ping_result -> P.IO ()
write_Ping_result oprot record = T.writeVal oprot $ from_Ping_result record
encode_Ping_result :: (T.Protocol p, T.Transport t) => p t -> Ping_result -> LBS.ByteString
encode_Ping_result oprot record = T.serializeVal oprot $ from_Ping_result record
to_Ping_result :: T.ThriftVal -> Ping_result
to_Ping_result (T.TStruct fields) = Ping_result{

  }
to_Ping_result _ = P.error "not a struct"
read_Ping_result :: (T.Transport t, T.Protocol p) => p t -> P.IO Ping_result
read_Ping_result iprot = to_Ping_result <$> T.readVal iprot (T.T_STRUCT typemap_Ping_result)
decode_Ping_result :: (T.Protocol p, T.Transport t) => p t -> LBS.ByteString -> Ping_result
decode_Ping_result iprot bs = to_Ping_result $ T.deserializeVal iprot (T.T_STRUCT typemap_Ping_result) bs
typemap_Ping_result :: T.TypeMap
typemap_Ping_result = Map.fromList []
default_Ping_result :: Ping_result
default_Ping_result = Ping_result{
}
data MyOp_args = MyOp_args  { myOp_args_a :: ServArgs
  , myOp_args_other :: LT.Text
  } deriving (P.Show,P.Eq,TY.Typeable)
instance H.Hashable MyOp_args where
  hashWithSalt salt record = salt   `H.hashWithSalt` myOp_args_a record   `H.hashWithSalt` myOp_args_other record  
instance QC.Arbitrary MyOp_args where 
  arbitrary = M.liftM MyOp_args (QC.arbitrary)
          `M.ap`(QC.arbitrary)
  shrink obj | obj == default_MyOp_args = []
             | P.otherwise = M.catMaybes
    [ if obj == default_MyOp_args{myOp_args_a = myOp_args_a obj} then P.Nothing else P.Just $ default_MyOp_args{myOp_args_a = myOp_args_a obj}
    , if obj == default_MyOp_args{myOp_args_other = myOp_args_other obj} then P.Nothing else P.Just $ default_MyOp_args{myOp_args_other = myOp_args_other obj}
    ]
from_MyOp_args :: MyOp_args -> T.ThriftVal
from_MyOp_args record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v20 -> P.Just (1, ("a",from_ServArgs _v20))) $ myOp_args_a record
  , (\_v20 -> P.Just (2, ("other",T.TString $ E.encodeUtf8 _v20))) $ myOp_args_other record
  ]
write_MyOp_args :: (T.Protocol p, T.Transport t) => p t -> MyOp_args -> P.IO ()
write_MyOp_args oprot record = T.writeVal oprot $ from_MyOp_args record
encode_MyOp_args :: (T.Protocol p, T.Transport t) => p t -> MyOp_args -> LBS.ByteString
encode_MyOp_args oprot record = T.serializeVal oprot $ from_MyOp_args record
to_MyOp_args :: T.ThriftVal -> MyOp_args
to_MyOp_args (T.TStruct fields) = MyOp_args{
  myOp_args_a = P.maybe (myOp_args_a default_MyOp_args) (\(_,_val22) -> (case _val22 of {T.TStruct _val23 -> (to_ServArgs (T.TStruct _val23)); _ -> P.error "wrong type"})) (Map.lookup (1) fields),
  myOp_args_other = P.maybe (myOp_args_other default_MyOp_args) (\(_,_val22) -> (case _val22 of {T.TString _val24 -> E.decodeUtf8 _val24; _ -> P.error "wrong type"})) (Map.lookup (2) fields)
  }
to_MyOp_args _ = P.error "not a struct"
read_MyOp_args :: (T.Transport t, T.Protocol p) => p t -> P.IO MyOp_args
read_MyOp_args iprot = to_MyOp_args <$> T.readVal iprot (T.T_STRUCT typemap_MyOp_args)
decode_MyOp_args :: (T.Protocol p, T.Transport t) => p t -> LBS.ByteString -> MyOp_args
decode_MyOp_args iprot bs = to_MyOp_args $ T.deserializeVal iprot (T.T_STRUCT typemap_MyOp_args) bs
typemap_MyOp_args :: T.TypeMap
typemap_MyOp_args = Map.fromList [(1,("a",(T.T_STRUCT typemap_ServArgs))),(2,("other",T.T_STRING))]
default_MyOp_args :: MyOp_args
default_MyOp_args = MyOp_args{
  myOp_args_a = default_ServArgs,
  myOp_args_other = ""}
data MyOp_result = MyOp_result  { myOp_result_success :: I.Int32
  } deriving (P.Show,P.Eq,TY.Typeable)
instance H.Hashable MyOp_result where
  hashWithSalt salt record = salt   `H.hashWithSalt` myOp_result_success record  
instance QC.Arbitrary MyOp_result where 
  arbitrary = M.liftM MyOp_result (QC.arbitrary)
  shrink obj | obj == default_MyOp_result = []
             | P.otherwise = M.catMaybes
    [ if obj == default_MyOp_result{myOp_result_success = myOp_result_success obj} then P.Nothing else P.Just $ default_MyOp_result{myOp_result_success = myOp_result_success obj}
    ]
from_MyOp_result :: MyOp_result -> T.ThriftVal
from_MyOp_result record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v27 -> P.Just (0, ("success",T.TI32 _v27))) $ myOp_result_success record
  ]
write_MyOp_result :: (T.Protocol p, T.Transport t) => p t -> MyOp_result -> P.IO ()
write_MyOp_result oprot record = T.writeVal oprot $ from_MyOp_result record
encode_MyOp_result :: (T.Protocol p, T.Transport t) => p t -> MyOp_result -> LBS.ByteString
encode_MyOp_result oprot record = T.serializeVal oprot $ from_MyOp_result record
to_MyOp_result :: T.ThriftVal -> MyOp_result
to_MyOp_result (T.TStruct fields) = MyOp_result{
  myOp_result_success = P.maybe (myOp_result_success default_MyOp_result) (\(_,_val29) -> (case _val29 of {T.TI32 _val30 -> _val30; _ -> P.error "wrong type"})) (Map.lookup (0) fields)
  }
to_MyOp_result _ = P.error "not a struct"
read_MyOp_result :: (T.Transport t, T.Protocol p) => p t -> P.IO MyOp_result
read_MyOp_result iprot = to_MyOp_result <$> T.readVal iprot (T.T_STRUCT typemap_MyOp_result)
decode_MyOp_result :: (T.Protocol p, T.Transport t) => p t -> LBS.ByteString -> MyOp_result
decode_MyOp_result iprot bs = to_MyOp_result $ T.deserializeVal iprot (T.T_STRUCT typemap_MyOp_result) bs
typemap_MyOp_result :: T.TypeMap
typemap_MyOp_result = Map.fromList [(0,("success",T.T_I32))]
default_MyOp_result :: MyOp_result
default_MyOp_result = MyOp_result{
  myOp_result_success = 0}
data SaveFood_args = SaveFood_args  { saveFood_args_nm :: LT.Text
  , saveFood_args_cost :: P.Double
  , saveFood_args_a :: P.Double
  , saveFood_args_c :: P.Double
  , saveFood_args_b1 :: P.Double
  , saveFood_args_b2 :: P.Double
  } deriving (P.Show,P.Eq,TY.Typeable)
instance H.Hashable SaveFood_args where
  hashWithSalt salt record = salt   `H.hashWithSalt` saveFood_args_nm record   `H.hashWithSalt` saveFood_args_cost record   `H.hashWithSalt` saveFood_args_a record   `H.hashWithSalt` saveFood_args_c record   `H.hashWithSalt` saveFood_args_b1 record   `H.hashWithSalt` saveFood_args_b2 record  
instance QC.Arbitrary SaveFood_args where 
  arbitrary = M.liftM SaveFood_args (QC.arbitrary)
          `M.ap`(QC.arbitrary)
          `M.ap`(QC.arbitrary)
          `M.ap`(QC.arbitrary)
          `M.ap`(QC.arbitrary)
          `M.ap`(QC.arbitrary)
  shrink obj | obj == default_SaveFood_args = []
             | P.otherwise = M.catMaybes
    [ if obj == default_SaveFood_args{saveFood_args_nm = saveFood_args_nm obj} then P.Nothing else P.Just $ default_SaveFood_args{saveFood_args_nm = saveFood_args_nm obj}
    , if obj == default_SaveFood_args{saveFood_args_cost = saveFood_args_cost obj} then P.Nothing else P.Just $ default_SaveFood_args{saveFood_args_cost = saveFood_args_cost obj}
    , if obj == default_SaveFood_args{saveFood_args_a = saveFood_args_a obj} then P.Nothing else P.Just $ default_SaveFood_args{saveFood_args_a = saveFood_args_a obj}
    , if obj == default_SaveFood_args{saveFood_args_c = saveFood_args_c obj} then P.Nothing else P.Just $ default_SaveFood_args{saveFood_args_c = saveFood_args_c obj}
    , if obj == default_SaveFood_args{saveFood_args_b1 = saveFood_args_b1 obj} then P.Nothing else P.Just $ default_SaveFood_args{saveFood_args_b1 = saveFood_args_b1 obj}
    , if obj == default_SaveFood_args{saveFood_args_b2 = saveFood_args_b2 obj} then P.Nothing else P.Just $ default_SaveFood_args{saveFood_args_b2 = saveFood_args_b2 obj}
    ]
from_SaveFood_args :: SaveFood_args -> T.ThriftVal
from_SaveFood_args record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v33 -> P.Just (1, ("nm",T.TString $ E.encodeUtf8 _v33))) $ saveFood_args_nm record
  , (\_v33 -> P.Just (2, ("cost",T.TDouble _v33))) $ saveFood_args_cost record
  , (\_v33 -> P.Just (3, ("a",T.TDouble _v33))) $ saveFood_args_a record
  , (\_v33 -> P.Just (4, ("c",T.TDouble _v33))) $ saveFood_args_c record
  , (\_v33 -> P.Just (5, ("b1",T.TDouble _v33))) $ saveFood_args_b1 record
  , (\_v33 -> P.Just (6, ("b2",T.TDouble _v33))) $ saveFood_args_b2 record
  ]
write_SaveFood_args :: (T.Protocol p, T.Transport t) => p t -> SaveFood_args -> P.IO ()
write_SaveFood_args oprot record = T.writeVal oprot $ from_SaveFood_args record
encode_SaveFood_args :: (T.Protocol p, T.Transport t) => p t -> SaveFood_args -> LBS.ByteString
encode_SaveFood_args oprot record = T.serializeVal oprot $ from_SaveFood_args record
to_SaveFood_args :: T.ThriftVal -> SaveFood_args
to_SaveFood_args (T.TStruct fields) = SaveFood_args{
  saveFood_args_nm = P.maybe (saveFood_args_nm default_SaveFood_args) (\(_,_val35) -> (case _val35 of {T.TString _val36 -> E.decodeUtf8 _val36; _ -> P.error "wrong type"})) (Map.lookup (1) fields),
  saveFood_args_cost = P.maybe (saveFood_args_cost default_SaveFood_args) (\(_,_val35) -> (case _val35 of {T.TDouble _val37 -> _val37; _ -> P.error "wrong type"})) (Map.lookup (2) fields),
  saveFood_args_a = P.maybe (saveFood_args_a default_SaveFood_args) (\(_,_val35) -> (case _val35 of {T.TDouble _val38 -> _val38; _ -> P.error "wrong type"})) (Map.lookup (3) fields),
  saveFood_args_c = P.maybe (saveFood_args_c default_SaveFood_args) (\(_,_val35) -> (case _val35 of {T.TDouble _val39 -> _val39; _ -> P.error "wrong type"})) (Map.lookup (4) fields),
  saveFood_args_b1 = P.maybe (saveFood_args_b1 default_SaveFood_args) (\(_,_val35) -> (case _val35 of {T.TDouble _val40 -> _val40; _ -> P.error "wrong type"})) (Map.lookup (5) fields),
  saveFood_args_b2 = P.maybe (saveFood_args_b2 default_SaveFood_args) (\(_,_val35) -> (case _val35 of {T.TDouble _val41 -> _val41; _ -> P.error "wrong type"})) (Map.lookup (6) fields)
  }
to_SaveFood_args _ = P.error "not a struct"
read_SaveFood_args :: (T.Transport t, T.Protocol p) => p t -> P.IO SaveFood_args
read_SaveFood_args iprot = to_SaveFood_args <$> T.readVal iprot (T.T_STRUCT typemap_SaveFood_args)
decode_SaveFood_args :: (T.Protocol p, T.Transport t) => p t -> LBS.ByteString -> SaveFood_args
decode_SaveFood_args iprot bs = to_SaveFood_args $ T.deserializeVal iprot (T.T_STRUCT typemap_SaveFood_args) bs
typemap_SaveFood_args :: T.TypeMap
typemap_SaveFood_args = Map.fromList [(1,("nm",T.T_STRING)),(2,("cost",T.T_DOUBLE)),(3,("a",T.T_DOUBLE)),(4,("c",T.T_DOUBLE)),(5,("b1",T.T_DOUBLE)),(6,("b2",T.T_DOUBLE))]
default_SaveFood_args :: SaveFood_args
default_SaveFood_args = SaveFood_args{
  saveFood_args_nm = "",
  saveFood_args_cost = 0,
  saveFood_args_a = 0,
  saveFood_args_c = 0,
  saveFood_args_b1 = 0,
  saveFood_args_b2 = 0}
data SaveFood_result = SaveFood_result  { saveFood_result_success :: P.Bool
  } deriving (P.Show,P.Eq,TY.Typeable)
instance H.Hashable SaveFood_result where
  hashWithSalt salt record = salt   `H.hashWithSalt` saveFood_result_success record  
instance QC.Arbitrary SaveFood_result where 
  arbitrary = M.liftM SaveFood_result (QC.arbitrary)
  shrink obj | obj == default_SaveFood_result = []
             | P.otherwise = M.catMaybes
    [ if obj == default_SaveFood_result{saveFood_result_success = saveFood_result_success obj} then P.Nothing else P.Just $ default_SaveFood_result{saveFood_result_success = saveFood_result_success obj}
    ]
from_SaveFood_result :: SaveFood_result -> T.ThriftVal
from_SaveFood_result record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v44 -> P.Just (0, ("success",T.TBool _v44))) $ saveFood_result_success record
  ]
write_SaveFood_result :: (T.Protocol p, T.Transport t) => p t -> SaveFood_result -> P.IO ()
write_SaveFood_result oprot record = T.writeVal oprot $ from_SaveFood_result record
encode_SaveFood_result :: (T.Protocol p, T.Transport t) => p t -> SaveFood_result -> LBS.ByteString
encode_SaveFood_result oprot record = T.serializeVal oprot $ from_SaveFood_result record
to_SaveFood_result :: T.ThriftVal -> SaveFood_result
to_SaveFood_result (T.TStruct fields) = SaveFood_result{
  saveFood_result_success = P.maybe (saveFood_result_success default_SaveFood_result) (\(_,_val46) -> (case _val46 of {T.TBool _val47 -> _val47; _ -> P.error "wrong type"})) (Map.lookup (0) fields)
  }
to_SaveFood_result _ = P.error "not a struct"
read_SaveFood_result :: (T.Transport t, T.Protocol p) => p t -> P.IO SaveFood_result
read_SaveFood_result iprot = to_SaveFood_result <$> T.readVal iprot (T.T_STRUCT typemap_SaveFood_result)
decode_SaveFood_result :: (T.Protocol p, T.Transport t) => p t -> LBS.ByteString -> SaveFood_result
decode_SaveFood_result iprot bs = to_SaveFood_result $ T.deserializeVal iprot (T.T_STRUCT typemap_SaveFood_result) bs
typemap_SaveFood_result :: T.TypeMap
typemap_SaveFood_result = Map.fromList [(0,("success",T.T_BOOL))]
default_SaveFood_result :: SaveFood_result
default_SaveFood_result = SaveFood_result{
  saveFood_result_success = P.False}
process_ping (seqid, iprot, oprot, handler) = do
  args <- read_Ping_args iprot
  (X.catch
    (do
      Iface.ping handler
      let res = default_Ping_result
      T.writeMessageBegin oprot ("ping", T.M_REPLY, seqid)
      write_Ping_result oprot res
      T.writeMessageEnd oprot
      T.tFlush (T.getTransport oprot))
    ((\_ -> do
      T.writeMessageBegin oprot ("ping", T.M_EXCEPTION, seqid)
      T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN "")
      T.writeMessageEnd oprot
      T.tFlush (T.getTransport oprot)) :: X.SomeException -> P.IO ()))
process_myOp (seqid, iprot, oprot, handler) = do
  args <- read_MyOp_args iprot
  (X.catch
    (do
      val <- Iface.myOp handler (myOp_args_a args) (myOp_args_other args)
      let res = default_MyOp_result{myOp_result_success = val}
      T.writeMessageBegin oprot ("myOp", T.M_REPLY, seqid)
      write_MyOp_result oprot res
      T.writeMessageEnd oprot
      T.tFlush (T.getTransport oprot))
    ((\_ -> do
      T.writeMessageBegin oprot ("myOp", T.M_EXCEPTION, seqid)
      T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN "")
      T.writeMessageEnd oprot
      T.tFlush (T.getTransport oprot)) :: X.SomeException -> P.IO ()))
process_saveFood (seqid, iprot, oprot, handler) = do
  args <- read_SaveFood_args iprot
  (X.catch
    (do
      val <- Iface.saveFood handler (saveFood_args_nm args) (saveFood_args_cost args) (saveFood_args_a args) (saveFood_args_c args) (saveFood_args_b1 args) (saveFood_args_b2 args)
      let res = default_SaveFood_result{saveFood_result_success = val}
      T.writeMessageBegin oprot ("saveFood", T.M_REPLY, seqid)
      write_SaveFood_result oprot res
      T.writeMessageEnd oprot
      T.tFlush (T.getTransport oprot))
    ((\_ -> do
      T.writeMessageBegin oprot ("saveFood", T.M_EXCEPTION, seqid)
      T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN "")
      T.writeMessageEnd oprot
      T.tFlush (T.getTransport oprot)) :: X.SomeException -> P.IO ()))
proc_ handler (iprot,oprot) (name,typ,seqid) = case name of
  "ping" -> process_ping (seqid,iprot,oprot,handler)
  "myOp" -> process_myOp (seqid,iprot,oprot,handler)
  "saveFood" -> process_saveFood (seqid,iprot,oprot,handler)
  _ -> do
    _ <- T.readVal iprot (T.T_STRUCT Map.empty)
    T.writeMessageBegin oprot (name,T.M_EXCEPTION,seqid)
    T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN_METHOD ("Unknown function " ++ LT.unpack name))
    T.writeMessageEnd oprot
    T.tFlush (T.getTransport oprot)
process handler (iprot, oprot) = do
  (name, typ, seqid) <- T.readMessageBegin iprot
  proc_ handler (iprot,oprot) (name,typ,seqid)
  T.readMessageEnd iprot
  P.return P.True
